ci:
  autofix_commit_msg: |
    style: auto fixes from pre-commit hooks
  autoupdate_commit_msg: |
    ci(pre-commit): autoupdate hook versions

repos:
  - repo: https://github.com/myint/autoflake
    rev: v1.4
    hooks:
      - id: autoflake
        name: Running autoflake in all files.
        files: trading_gym/
        args:
          - --in-place
          - --remove-all-unused-imports
          - --ignore-init-module-imports

  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
        name: Running black in all files.
        files: trading_gym/

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: Running isort in all files.
        files: trading_gym/
        args: [--profile=black]

  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        name: Running flake8 in all files.
        files: trading_gym/
        args: [--config=.flake8]

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.3.1
    hooks:
    -   id: pyupgrade
        name: Running pyupgrade in all files.
        files: trading_gym/
        args: [--py39-plus]
